### ISSUE TITLE
Content Review Checklist

### ISSUE THREAD

**Issue by justineechen** [OpenLiberty/draft-guide-cloud-aws#13]
Content Review<br/><br/>- [ ] Content coverage<br/>- [ ] Code structure<br/>- [ ] Ensure direction of the guide is accurate<br/>- [ ] Ensure flow of the guide is smooth<br/>- [ ] Ensure quality of the guide meets requirements and expectations<br/>- [ ] Ensure requirements are clearly stated

**Comment by andrewdes** [comment]
Was done here: https://github.com/OpenLiberty/draft-guide-cloud-aws/issues/23
