### ISSUE TITLE
Gilbert's feedback

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/draft-guide-cloud-aws#18]
- [x] typo: 
  - `Sercice` at the very beginning
  - `JVM systems properties` to `JVM system properties` in "What you’ll learn" section
- [x] In Prereq , 
  - Docker: change "**official Docker documentation**" to  "official **Docker** documentation" 
  - kubectl: change "**official documentation**" to "official **Install and Set Up kubectl** documentation."
  -  eksctl :  "eksctl release page" -> "eksctl releases page " or " eksctl Releases page "
  - AWS CLI: "**official documentation**" ->  "official **Download Python** documentation" 
- [x] No need from "Once you have Python installed ....the **installing the AWS CLI** documentation." but in the AWS CLI bullet, ask reader to set up awscli by the instruction in the **Installing the AWS CLI** documentation
  - keep the content from "To verify that AWS CLI ..." 
- [x] "aws configure" instruction should be after create a user instructions. Reorg that section.
- [x] suggest to ask reader to capture the Access key ID and Secret access key during create a user
- [x] change `123` to `[password_string]` and `123456` to `[aws_account_id]`
```docker login -u AWS -p 123 https://123456.dkr.ecr.[region].amazonaws.com``` to
```docker login -u AWS -p [password_string] https://[aws_account_id].dkr.ecr.[region].amazonaws.com``` 
- [x] inconsistent to use `1234`, `12345`, and `123456`, should use an number close to a similar account id, e.g. `208873072923` and make a statement it is aws_account_id being used in the examples
- [x] At the beginning of the section "Deploying microservices to Amazon Elastic Container Service for Kubernetes (EKS)", should have a summary of the overall achievement in this section, or brief explain what will do in this section? Then readers can easily follow the steps.
- [ ] why "Provisioning a cluster" is the first sub-section? can it be done later?
- [x] "When the cluster is finished creating," -> "When the cluster is created,"
- [x] suggest to change the following statement as
"If you’re using Docker for Windows, on the Docker Desktop _General Setting_ page, ensure that the option `Expose daemon on tcp://localhost:2375 without TLS` is enabled.
"
- [x] couple of places still using `name and ping`
- [x] Under "Update the kubernetes.yaml file.", the `system` and `inventory` can have a hotspot again sepcifically
- [x] Instead of just tell reader to use `curl`, 
"Then `curl` or visit the following URLs to access your microservices, substituting the appropriate hostname:"
- [x] need update "Deploying new version of name microservice" -> "....system microservice"
- [x] At the beginning of the sub-section "Deploying new version of name microservice", should have a summary of the overall achievement in this section, or brief explain what will do in this section? Then readers can easily follow the steps.
- [x] under section "Deploying new version of name microservice",  suggest
  - "Use the following Maven..." -> "After updating the `system` microservice, use the following Maven..."
  - "Use Maven to package your microservice." -> "Use Maven to repackage your microservice."
- [x] the tearing down section should tell how to clean the repos `awsguide/system` and  `awsguide/inventory`

**Comment by andrewdes** [comment]
@gkwan-ibm 
>  why "Provisioning a cluster" is the first sub-section? can it be done later?

See discussion here: https://github.com/OpenLiberty/draft-guide-cloud-ibm/issues/19

**Comment by andrewdes** [comment]
All this feedback was addressed and merged in #20
