### ISSUE TITLE
Review comments

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/draft-guide-cloud-aws#23]
- Consider "What is Kubernetes?" and "Why use Kubernetes service in the cloud?" sub-sections under "What you'll learn" instead of a top-level section before "What you'll learn".

- For "Why use Kubernetes service in the cloud?", add a reference to DevOps e.g. work locally first and then push to cloud for further testing as part of DevOps so useful to understand how to deploy to a hosted Kubernetes service.

- What's the thinking behind the section on deploying a new version of the system service?  Should it be a top-level section?

- "Where to next?" can have the Kube-MP guides as well as the Istio Intro.

- The page-description, page-seo-title and page-seo-description need work. The title too.  We should make the Cloud guides to be consistent with each other?

- Should have a placeholder issue to switch the link for the Docker guide mentioned to the new one under development.

@gkwan-ibm

**Comment by andrewdes** [comment]
All the feedback has been addressed and merged here: https://github.com/OpenLiberty/draft-guide-cloud-aws/pull/25
